import { type ThemeColors, fontSize, fontWeight, radius, withOpacity } from "@/styles/theme";
import { StyleSheet } from "react-native";

export const makeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    loadingWrap: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },
    spinner: {
      width: 32,
      height: 32,
      borderRadius: 16,
      borderWidth: 2,
      borderColor: withOpacity(colors.primary, 0.3),
      borderTopColor: colors.primary,
    },
    loadingText: { fontSize: fontSize.sm, color: colors.mutedForeground },
    header: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 12,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    headerTitle: {
      fontSize: fontSize["2xl"],
      fontWeight: fontWeight.bold,
      color: colors.foreground,
    },
    searchToggle: {
      width: 36,
      height: 36,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
    },
    statsRow: { flexDirection: "row", gap: 12, marginTop: 10 },
    statBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: colors.muted,
      borderRadius: radius.lg,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    statValue: { fontSize: fontSize.sm, fontWeight: fontWeight.semibold, color: colors.foreground },
    statLabel: { fontSize: 12, color: colors.mutedForeground },
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.muted,
      borderRadius: radius.lg,
      paddingHorizontal: 12,
      height: 36,
      gap: 8,
      marginTop: 10,
    },
    searchInput: { flex: 1, fontSize: fontSize.sm, color: colors.foreground, padding: 0 },
    emptyWrap: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 24 },
    emptyIconWrap: {
      width: 80,
      height: 80,
      borderRadius: radius.full,
      backgroundColor: colors.muted,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 16,
    },
    emptyTitle: {
      fontSize: fontSize.lg,
      fontWeight: fontWeight.semibold,
      color: colors.foreground,
      marginBottom: 8,
    },
    emptyHint: {
      fontSize: fontSize.sm,
      color: colors.mutedForeground,
      textAlign: "center",
      maxWidth: 260,
    },
    listContent: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 24 },
    notebookCard: {
      flexDirection: "row",
      alignItems: "flex-start",
      backgroundColor: colors.card,
      borderRadius: radius.xl,
      borderWidth: 0.5,
      borderColor: colors.border,
      padding: 12,
      marginBottom: 12,
      gap: 12,
    },
    notebookCover: {
      width: 44,
      height: 64,
      borderRadius: radius.sm,
      backgroundColor: colors.muted,
    },
    notebookCoverFallback: {
      width: 44,
      height: 64,
      borderRadius: radius.sm,
      backgroundColor: colors.muted,
      alignItems: "center",
      justifyContent: "center",
    },
    notebookInfo: { flex: 1, gap: 4 },
    notebookTitle: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.medium,
      color: colors.foreground,
    },
    notebookAuthor: { fontSize: fontSize.xs, color: colors.mutedForeground },
    notebookStats: { flexDirection: "row", alignItems: "center", gap: 12, marginTop: 4 },
    notebookStatItem: { flexDirection: "row", alignItems: "center", gap: 4 },
    notebookStatText: { fontSize: fontSize.xs, color: colors.mutedForeground },
    notebookBadge: {
      backgroundColor: colors.muted,
      borderRadius: radius.full,
      paddingHorizontal: 8,
      paddingVertical: 2,
    },
    notebookBadgeText: { fontSize: fontSize.xs, color: colors.mutedForeground },
    detailHeader: { borderBottomWidth: 0.5, borderBottomColor: colors.border },
    detailHeaderTop: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    backBtn: {
      width: 32,
      height: 32,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
    },
    detailCover: { width: 28, height: 40, borderRadius: 4, backgroundColor: colors.muted },
    detailCoverFallback: {
      width: 28,
      height: 40,
      borderRadius: 4,
      backgroundColor: colors.muted,
      alignItems: "center",
      justifyContent: "center",
    },
    detailHeaderInfo: { flex: 1, minWidth: 0 },
    detailTitle: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.semibold,
      color: colors.foreground,
    },
    detailAuthor: { fontSize: fontSize.xs, color: colors.mutedForeground },
    exportBtn: {
      width: 32,
      height: 32,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
    },
    detailTabRow: { flexDirection: "column", gap: 8, paddingHorizontal: 16, paddingVertical: 12 },
    tabSwitcher: {
      flexDirection: "row",
      borderWidth: 0.5,
      borderColor: colors.border,
      borderRadius: radius.lg,
      padding: 2,
    },
    tabBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: radius.md,
    },
    tabBtnActive: { backgroundColor: colors.primary },
    tabBtnText: {
      fontSize: fontSize.xs,
      fontWeight: fontWeight.medium,
      color: colors.mutedForeground,
    },
    tabBtnTextActive: { color: colors.primaryForeground },
    detailSearch: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: colors.muted,
      borderRadius: radius.lg,
      paddingHorizontal: 12,
      height: 32,
    },
    detailSearchInput: { flex: 1, fontSize: fontSize.sm, color: colors.foreground, padding: 0 },
    knowledgeStatusBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
      minHeight: 32,
    },
    knowledgeStatusPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: colors.muted,
      borderRadius: radius.md,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    knowledgeStatusText: {
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeStatusMeta: {
      flexShrink: 1,
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      textAlign: "right",
    },
    detailEmpty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 },
    detailEmptyText: { fontSize: fontSize.sm, color: colors.mutedForeground },
    detailList: { flex: 1, paddingHorizontal: 16 },
    knowledgeLoading: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },
    knowledgeRoot: { flex: 1, backgroundColor: colors.background },
    knowledgeScroll: { flex: 1 },
    knowledgeContent: {
      paddingHorizontal: 12,
      paddingTop: 2,
      paddingBottom: 30,
      gap: 10,
    },
    knowledgeDocumentContent: {
      paddingHorizontal: 12,
      paddingTop: 8,
      paddingBottom: 18,
      gap: 10,
    },
    knowledgeVaultHeader: {
      minHeight: 50,
      zIndex: 2,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
      backgroundColor: colors.background,
      paddingHorizontal: 0,
      paddingBottom: 8,
    },
    knowledgeVaultIcon: {
      width: 30,
      height: 30,
      borderRadius: radius.md,
      backgroundColor: withOpacity(colors.primary, 0.1),
      alignItems: "center",
      justifyContent: "center",
    },
    knowledgeVaultText: { minWidth: 0 },
    knowledgeVaultEyebrow: {
      fontSize: 11,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
      lineHeight: 14,
    },
    knowledgeVaultTitle: {
      marginTop: 0,
      fontSize: fontSize.md,
      lineHeight: 21,
      color: colors.foreground,
      fontWeight: fontWeight.semibold,
    },
    knowledgeVaultPath: {
      marginTop: 2,
      fontSize: 11,
      lineHeight: 14,
      color: colors.mutedForeground,
    },
    knowledgeVaultPathScroll: {
      marginTop: 4,
      maxHeight: 24,
    },
    knowledgeVaultPathTrail: {
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
      paddingRight: 14,
    },
    knowledgeVaultPathSegment: {
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
      maxWidth: 240,
    },
    knowledgeVaultPathSlash: {
      fontSize: 11,
      lineHeight: 14,
      color: withOpacity(colors.mutedForeground, 0.5),
      fontWeight: fontWeight.medium,
    },
    knowledgeVaultPathChip: {
      maxWidth: 180,
      minHeight: 22,
      flexDirection: "row",
      alignItems: "center",
      gap: 0,
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "transparent",
      backgroundColor: "transparent",
      justifyContent: "flex-start",
      paddingHorizontal: 1,
      paddingVertical: 2,
    },
    knowledgeVaultPathChipActive: {
      backgroundColor: "transparent",
      borderBottomWidth: 1,
      borderBottomColor: withOpacity(colors.foreground, 0.36),
    },
    knowledgeVaultPathChipText: {
      flexShrink: 1,
      fontSize: 11,
      lineHeight: 14,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeVaultPathChipTextActive: {
      color: colors.foreground,
      fontWeight: fontWeight.semibold,
    },
    knowledgeVaultStats: {
      alignItems: "flex-end",
      justifyContent: "center",
      gap: 3,
      maxWidth: 98,
    },
    knowledgeVaultStatText: {
      fontSize: 11,
      lineHeight: 14,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeDocumentEyebrow: {
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
      marginBottom: 4,
    },
    knowledgeDocumentScreen: {
      gap: 12,
      paddingTop: 2,
    },
    knowledgeDocumentFullScreen: {
      flex: 1,
      paddingHorizontal: 14,
      paddingTop: 8,
      paddingBottom: 12,
    },
    knowledgeDocumentKeyboardAvoider: {
      flex: 1,
    },
    knowledgeDocumentCanvasHeader: {
      minHeight: 66,
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
      paddingBottom: 10,
    },
    knowledgeDocumentBackButton: {
      width: 36,
      height: 36,
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: "center",
      justifyContent: "center",
    },
    knowledgeDocumentCanvasTitleBlock: {
      flex: 1,
      minWidth: 0,
    },
    knowledgeCanvasTitleInput: {
      minHeight: 34,
      maxHeight: 58,
      padding: 0,
      fontSize: fontSize.xl,
      lineHeight: 27,
      color: colors.foreground,
      fontWeight: fontWeight.bold,
    },
    knowledgeCanvasPath: {
      marginTop: 3,
      fontSize: fontSize.xs,
      lineHeight: 17,
      color: colors.mutedForeground,
    },
    knowledgeCanvasMeta: {
      marginTop: 3,
      fontSize: 11,
      lineHeight: 14,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeDocumentActionRail: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingTop: 2,
    },
    knowledgeCanvasStatus: {
      width: 32,
      height: 32,
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: "center",
      justifyContent: "center",
    },
    knowledgeCanvasIconButton: {
      width: 32,
      height: 32,
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: "center",
      justifyContent: "center",
    },
    knowledgeCanvasSaveText: {
      marginTop: -6,
      alignSelf: "flex-end",
      fontSize: 11,
      lineHeight: 14,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeDocumentCanvas: {
      flex: 1,
      minHeight: 540,
      borderRadius: radius.sm,
      borderWidth: 0,
      overflow: "hidden",
      backgroundColor: colors.background,
    },
    knowledgeMoveSheetBackdrop: {
      flex: 1,
      backgroundColor: withOpacity("#000000", 0.28),
    },
    knowledgeMoveSheet: {
      position: "absolute",
      left: 12,
      right: 12,
      bottom: 12,
      maxHeight: "58%",
      borderRadius: radius.xl,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      padding: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.22,
      shadowRadius: 18,
      elevation: 10,
    },
    knowledgeMoveSheetHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      paddingBottom: 10,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    knowledgeMoveSheetTitleBlock: { flex: 1, minWidth: 0 },
    knowledgeMoveSheetTitle: {
      fontSize: fontSize.sm,
      color: colors.foreground,
      fontWeight: fontWeight.semibold,
      lineHeight: 19,
    },
    knowledgeMoveSheetSubtitle: {
      marginTop: 2,
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      lineHeight: 16,
    },
    knowledgeMoveSheetClose: {
      width: 32,
      height: 32,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radius.md,
      backgroundColor: colors.muted,
    },
    knowledgeRenameBody: {
      gap: 12,
      paddingTop: 12,
    },
    knowledgeRenameInput: {
      minHeight: 42,
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.background,
      paddingHorizontal: 12,
      paddingVertical: 9,
      fontSize: fontSize.sm,
      color: colors.foreground,
    },
    knowledgeImportSheet: {
      position: "absolute",
      left: 10,
      right: 10,
      bottom: 10,
      maxHeight: "82%",
      borderRadius: radius.xl,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      paddingHorizontal: 12,
      paddingTop: 8,
      paddingBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.24,
      shadowRadius: 18,
      elevation: 12,
    },
    knowledgeImportSheetHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 10,
      paddingBottom: 10,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    knowledgeImportSheetTitleWrap: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
    },
    knowledgeImportSheetIcon: {
      width: 32,
      height: 32,
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderColor: withOpacity(colors.primary, 0.22),
      backgroundColor: withOpacity(colors.primary, 0.1),
      alignItems: "center",
      justifyContent: "center",
    },
    knowledgeImportSheetTitleBlock: { flex: 1, minWidth: 0 },
    knowledgeImportSheetTitle: {
      fontSize: fontSize.sm,
      lineHeight: 19,
      color: colors.foreground,
      fontWeight: fontWeight.semibold,
    },
    knowledgeImportSheetSubtitle: {
      marginTop: 3,
      fontSize: fontSize.xs,
      lineHeight: 17,
      color: colors.mutedForeground,
    },
    knowledgeImportSheetScroll: { marginTop: 10 },
    knowledgeImportSheetContent: { gap: 8, paddingBottom: 4 },
    knowledgeImportItem: {
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.background,
      paddingHorizontal: 11,
      paddingVertical: 10,
    },
    knowledgeImportItemHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 10,
    },
    knowledgeImportItemTitleBlock: { flex: 1, minWidth: 0 },
    knowledgeImportItemTitle: {
      fontSize: fontSize.sm,
      lineHeight: 18,
      color: colors.foreground,
      fontWeight: fontWeight.semibold,
    },
    knowledgeImportItemPath: {
      marginTop: 2,
      fontSize: 11,
      lineHeight: 15,
      color: colors.mutedForeground,
    },
    knowledgeImportSourcePath: {
      marginTop: 1,
      fontSize: 10,
      lineHeight: 14,
      color: withOpacity(colors.mutedForeground, 0.78),
    },
    knowledgeImportDestination: {
      marginTop: 5,
      minHeight: 18,
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
    },
    knowledgeImportDestinationText: {
      flex: 1,
      minWidth: 0,
      fontSize: 11,
      lineHeight: 15,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeImportItemBadge: {
      overflow: "hidden",
      borderRadius: radius.sm,
      backgroundColor: colors.muted,
      paddingHorizontal: 8,
      paddingVertical: 4,
      fontSize: 11,
      lineHeight: 14,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeImportItemPreview: {
      marginTop: 8,
      fontSize: fontSize.xs,
      lineHeight: 18,
      color: colors.mutedForeground,
    },
    knowledgeImportMetaRow: {
      marginTop: 8,
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
    },
    knowledgeImportTag: {
      maxWidth: 118,
      overflow: "hidden",
      borderRadius: radius.sm,
      backgroundColor: colors.muted,
      paddingHorizontal: 7,
      paddingVertical: 4,
      fontSize: 11,
      lineHeight: 14,
      color: colors.mutedForeground,
    },
    knowledgeImportWarning: {
      overflow: "hidden",
      borderRadius: radius.sm,
      backgroundColor: withOpacity("#f59e0b", 0.12),
      paddingHorizontal: 7,
      paddingVertical: 4,
      fontSize: 11,
      lineHeight: 14,
      color: "#b45309",
      fontWeight: fontWeight.medium,
    },
    knowledgeImportHiddenText: {
      paddingHorizontal: 2,
      fontSize: fontSize.xs,
      lineHeight: 16,
      color: colors.mutedForeground,
    },
    knowledgeImportFooter: {
      gap: 10,
      marginTop: 10,
      paddingTop: 10,
      borderTopWidth: 0.5,
      borderTopColor: colors.border,
    },
    knowledgeImportSafeHint: {
      fontSize: fontSize.xs,
      lineHeight: 17,
      color: colors.mutedForeground,
    },
    knowledgeImportFooterActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 8,
    },
    knowledgeImportSecondaryButton: {
      minHeight: 36,
      borderRadius: radius.md,
      backgroundColor: colors.muted,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    knowledgeImportSecondaryButtonText: {
      fontSize: fontSize.sm,
      color: colors.foreground,
      fontWeight: fontWeight.medium,
    },
    knowledgeImportPrimaryButton: {
      minHeight: 36,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      borderRadius: radius.md,
      backgroundColor: colors.primary,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    knowledgeImportButtonDisabled: { opacity: 0.62 },
    knowledgeImportPrimaryButtonText: {
      fontSize: fontSize.sm,
      color: colors.primaryForeground,
      fontWeight: fontWeight.semibold,
    },
    knowledgeContextSheet: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      maxHeight: "82%",
      borderTopLeftRadius: radius.xl,
      borderTopRightRadius: radius.xl,
      borderWidth: 0.5,
      borderBottomWidth: 0,
      borderColor: colors.border,
      backgroundColor: colors.card,
      paddingHorizontal: 14,
      paddingTop: 8,
      paddingBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -10 },
      shadowOpacity: 0.18,
      shadowRadius: 20,
      elevation: 12,
    },
    knowledgeContextSheetHandle: {
      alignSelf: "center",
      width: 36,
      height: 4,
      borderRadius: radius.full,
      backgroundColor: colors.border,
      marginBottom: 10,
    },
    knowledgeContextSheetHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      paddingBottom: 10,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    knowledgeContextSheetTitleBlock: { flex: 1, minWidth: 0 },
    knowledgeContextSheetTitle: {
      fontSize: fontSize.md,
      color: colors.foreground,
      fontWeight: fontWeight.semibold,
      lineHeight: 21,
    },
    knowledgeContextSheetSubtitle: {
      marginTop: 2,
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      lineHeight: 16,
    },
    knowledgeContextSheetScroll: {
      marginTop: 12,
    },
    knowledgeContextSheetContent: {
      gap: 12,
      paddingBottom: 18,
    },
    knowledgeMoveTargetScroll: { marginTop: 10 },
    knowledgeMoveTargetList: { gap: 6, paddingBottom: 4 },
    knowledgeCreateTargetList: { marginTop: 10 },
    knowledgeMoveTarget: {
      minHeight: 44,
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.background,
      paddingRight: 12,
      paddingVertical: 8,
    },
    knowledgeMoveTargetIcon: {
      width: 28,
      height: 28,
      borderRadius: radius.md,
      backgroundColor: colors.muted,
      alignItems: "center",
      justifyContent: "center",
    },
    knowledgeMoveTargetTextBlock: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    knowledgeMoveTargetText: {
      flex: 1,
      minWidth: 0,
      fontSize: fontSize.sm,
      color: colors.foreground,
      fontWeight: fontWeight.medium,
      lineHeight: 18,
    },
    knowledgeMoveTargetTitle: {
      fontSize: fontSize.sm,
      color: colors.foreground,
      fontWeight: fontWeight.medium,
      lineHeight: 18,
    },
    knowledgeMoveTargetPath: {
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      lineHeight: 16,
    },
    knowledgeMoveTargetDangerText: {
      color: colors.destructive,
    },
    knowledgeTagWrap: { gap: 7 },
    knowledgeTagLabel: {
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeTagRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 7,
    },
    knowledgeTagChip: {
      minHeight: 30,
      maxWidth: 136,
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.muted,
      paddingHorizontal: 9,
      paddingVertical: 6,
    },
    knowledgeTagText: {
      flexShrink: 1,
      fontSize: fontSize.xs,
      color: colors.foreground,
      fontWeight: fontWeight.medium,
    },
    knowledgeTagRemove: {
      fontSize: fontSize.sm,
      lineHeight: 16,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeTagInput: {
      minWidth: 96,
      minHeight: 30,
      flexGrow: 1,
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderStyle: "dashed",
      borderColor: colors.border,
      paddingHorizontal: 9,
      paddingVertical: 6,
      fontSize: fontSize.xs,
      color: colors.foreground,
    },
    knowledgeTagInputPlaceholder: {
      color: colors.mutedForeground,
    },
    knowledgeExplorerCard: {
      backgroundColor: colors.background,
      borderRadius: radius.sm,
      borderWidth: 0,
      padding: 0,
      gap: 7,
    },
    knowledgeExplorerHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      paddingHorizontal: 0,
      paddingTop: 1,
      paddingBottom: 8,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    knowledgeExplorerTitleBlock: { flex: 1, minWidth: 0 },
    knowledgeExplorerHint: {
      marginTop: 2,
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      lineHeight: 16,
    },
    knowledgeExplorerCreateButton: {
      width: 32,
      height: 32,
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderColor: withOpacity(colors.primary, 0.28),
      backgroundColor: withOpacity(colors.primary, 0.06),
      alignItems: "center",
      justifyContent: "center",
    },
    knowledgeDocumentSearch: {
      minHeight: 34,
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      borderRadius: radius.sm,
      borderWidth: 0.5,
      borderColor: withOpacity(colors.border, 0.62),
      backgroundColor: withOpacity(colors.muted, 0.36),
      paddingHorizontal: 10,
    },
    knowledgeDocumentSearchInput: {
      flex: 1,
      minHeight: 32,
      paddingVertical: 6,
      fontSize: fontSize.xs,
      color: colors.foreground,
    },
    knowledgeTreeList: {
      borderRadius: radius.sm,
      backgroundColor: colors.background,
      gap: 1,
      borderTopWidth: 0.5,
      borderTopColor: withOpacity(colors.border, 0.72),
      borderLeftWidth: 0,
      paddingTop: 4,
      paddingBottom: 3,
      paddingLeft: 0,
    },
    knowledgeTreeNode: {
      position: "relative",
      minHeight: 40,
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      borderRadius: radius.sm,
      borderWidth: 0.5,
      borderColor: "transparent",
      paddingRight: 10,
      paddingVertical: 4,
    },
    knowledgeTreeConnector: {
      position: "absolute",
      top: 7,
      bottom: 7,
      width: 0.5,
      backgroundColor: colors.border,
    },
    knowledgeTreeNodeActive: {
      borderLeftWidth: 2,
      borderLeftColor: colors.primary,
      borderColor: withOpacity(colors.primary, 0.18),
      backgroundColor: withOpacity(colors.primary, 0.045),
    },
    knowledgeTreeNodeAncestor: {
      borderLeftWidth: 2,
      borderLeftColor: withOpacity(colors.border, 0.85),
      borderColor: withOpacity(colors.border, 0.58),
      backgroundColor: withOpacity(colors.mutedForeground, 0.045),
    },
    knowledgeTreeToggle: {
      width: 22,
      height: 28,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radius.sm,
    },
    knowledgeTreeToggleExpanded: {
      transform: [{ rotate: "90deg" }],
    },
    knowledgeTreeToggleSpacer: { width: 22, height: 28 },
    knowledgeTreeIcon: {
      width: 20,
      height: 22,
      borderRadius: radius.sm,
      backgroundColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
    },
    knowledgeTreeIconActive: {
      backgroundColor: "transparent",
    },
    knowledgeTreeTextBlock: { flex: 1, minWidth: 0 },
    knowledgeTreeTitle: {
      fontSize: fontSize.xs,
      color: colors.foreground,
      fontWeight: fontWeight.semibold,
      lineHeight: 17,
    },
    knowledgeTreeTitleActive: { color: colors.primary },
    knowledgeTreeTitleAncestor: { color: colors.foreground },
    knowledgeTreeMeta: {
      marginTop: 1,
      fontSize: 11,
      color: colors.mutedForeground,
      lineHeight: 14,
    },
    knowledgeTreeCount: {
      minWidth: 22,
      textAlign: "right",
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeTreeCountActive: { color: withOpacity(colors.primary, 0.78) },
    knowledgeDocumentEmptyResult: {
      minHeight: 48,
      borderRadius: radius.sm,
      backgroundColor: colors.muted,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    knowledgeDocumentEmptyResultText: {
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      textAlign: "center",
    },
    knowledgeSectionTitle: {
      fontSize: fontSize.sm,
      color: colors.foreground,
      fontWeight: fontWeight.semibold,
    },
    knowledgeEditorFrame: {
      minHeight: 0,
      borderRadius: radius.lg,
      borderWidth: 0.5,
      borderColor: colors.border,
      overflow: "hidden",
      backgroundColor: colors.background,
    },
    knowledgeFolderOverview: {
      borderRadius: radius.sm,
      borderWidth: 0,
      backgroundColor: colors.background,
      paddingHorizontal: 0,
      paddingVertical: 0,
      gap: 11,
    },
    knowledgeFolderHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 0,
      paddingTop: 2,
      paddingBottom: 9,
      backgroundColor: colors.background,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
      borderLeftWidth: 0,
    },
    knowledgeFolderLead: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 11,
    },
    knowledgeFolderLeadIcon: {
      width: 38,
      height: 38,
      borderRadius: radius.md,
      backgroundColor: withOpacity(colors.primary, 0.1),
      alignItems: "center",
      justifyContent: "center",
    },
    knowledgeFolderLeadText: { flex: 1, minWidth: 0 },
    knowledgeFolderTitle: {
      fontSize: fontSize.sm,
      color: colors.foreground,
      fontWeight: fontWeight.semibold,
      lineHeight: 19,
    },
    knowledgeFolderDescription: {
      marginTop: 2,
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      lineHeight: 16,
    },
    knowledgeFolderMeta: {
      marginTop: 2,
      fontSize: 11,
      color: colors.mutedForeground,
      lineHeight: 14,
      fontWeight: fontWeight.medium,
    },
    knowledgeFolderIconAction: {
      minWidth: 31,
      height: 31,
      flexDirection: "row",
      borderRadius: radius.sm,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
      paddingHorizontal: 8,
    },
    knowledgeFolderIconActionText: {
      maxWidth: 46,
      fontSize: 11,
      color: colors.primary,
      fontWeight: fontWeight.semibold,
      lineHeight: 14,
    },
    knowledgeFolderActionRow: {
      flexDirection: "row",
      gap: 8,
      marginTop: 14,
      width: "100%",
    },
    knowledgeFolderAction: {
      flex: 1,
      minHeight: 38,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      borderRadius: radius.sm,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    knowledgeFolderActionText: {
      fontSize: fontSize.xs,
      color: colors.primary,
      fontWeight: fontWeight.semibold,
    },
    knowledgeFolderEmpty: {
      minHeight: 116,
      borderRadius: 0,
      borderWidth: 0.5,
      borderStyle: "dashed",
      borderColor: colors.border,
      backgroundColor: withOpacity(colors.muted, 0.24),
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 18,
      paddingVertical: 18,
    },
    knowledgeFolderEmptyTitle: {
      fontSize: fontSize.sm,
      color: colors.foreground,
      fontWeight: fontWeight.semibold,
      textAlign: "center",
    },
    knowledgeFolderEmptyHint: {
      marginTop: 6,
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      lineHeight: 18,
      textAlign: "center",
    },
    knowledgeFolderItemList: {
      gap: 0,
      borderTopWidth: 0.5,
      borderBottomWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    knowledgeFolderGroupStack: { gap: 14 },
    knowledgeFolderGroup: { gap: 6 },
    knowledgeFolderGroupHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
      paddingHorizontal: 2,
      paddingBottom: 6,
    },
    knowledgeFolderGroupTitle: {
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      fontWeight: fontWeight.semibold,
      textTransform: "uppercase",
    },
    knowledgeFolderGroupCount: {
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeFolderItem: {
      minHeight: 48,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      borderRadius: 0,
      borderWidth: 0,
      borderBottomWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.background,
      paddingHorizontal: 0,
      paddingVertical: 6,
    },
    knowledgeFolderItemMain: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    knowledgeFolderItemMore: {
      width: 32,
      height: 32,
      borderRadius: radius.sm,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    knowledgeFolderItemIcon: {
      width: 22,
      height: 28,
      borderRadius: radius.sm,
      backgroundColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
    },
    knowledgeFolderIcon: {
      backgroundColor: "transparent",
      borderWidth: 0,
      borderColor: "transparent",
    },
    knowledgeFolderItemText: { flex: 1, minWidth: 0 },
    knowledgeFolderItemTitle: {
      fontSize: fontSize.sm,
      color: colors.foreground,
      fontWeight: fontWeight.semibold,
      lineHeight: 18,
    },
    knowledgeFolderItemMeta: {
      marginTop: 2,
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      lineHeight: 16,
    },
    knowledgeFolderItemCount: {
      minWidth: 22,
      paddingHorizontal: 2,
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
      textAlign: "center",
    },
    knowledgeSourcesCard: {
      backgroundColor: colors.card,
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderColor: colors.border,
      padding: 12,
      gap: 10,
    },
    knowledgeSourcesHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    knowledgeOpenButton: {
      borderRadius: radius.md,
      backgroundColor: colors.muted,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    knowledgeOpenButtonText: {
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeRelationLoading: {
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
    },
    knowledgeOutlineTitleWrap: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    knowledgeOutlineList: {
      gap: 4,
    },
    knowledgeOutlineRow: {
      minHeight: 32,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      borderRadius: radius.md,
      backgroundColor: colors.background,
      paddingRight: 10,
      paddingVertical: 6,
    },
    knowledgeOutlineDot: {
      width: 5,
      height: 5,
      borderRadius: radius.full,
      backgroundColor: withOpacity(colors.primary, 0.52),
    },
    knowledgeOutlineLevel: {
      width: 22,
      fontSize: 10,
      lineHeight: 13,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeOutlineText: {
      flex: 1,
      minWidth: 0,
      fontSize: fontSize.xs,
      lineHeight: 17,
      color: colors.foreground,
      fontWeight: fontWeight.medium,
    },
    knowledgeRelationGroupTitle: {
      marginTop: 2,
      marginBottom: -2,
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    knowledgeSummaryCard: {
      backgroundColor: colors.card,
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderColor: colors.border,
      padding: 12,
      gap: 10,
    },
    knowledgeSummaryHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 10,
    },
    knowledgeSummaryTitleWrap: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
    },
    knowledgeSummaryIcon: {
      width: 30,
      height: 30,
      borderRadius: radius.md,
      backgroundColor: withOpacity(colors.primary, 0.12),
      alignItems: "center",
      justifyContent: "center",
    },
    knowledgeSummaryTitleTextWrap: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    knowledgeSummaryStatus: {
      fontSize: fontSize.xs,
      lineHeight: 16,
      fontWeight: fontWeight.medium,
    },
    knowledgeSummaryButton: {
      minHeight: 34,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
      borderRadius: radius.md,
      borderWidth: 0.5,
      borderColor: withOpacity(colors.primary, 0.28),
      backgroundColor: withOpacity(colors.primary, 0.08),
      paddingHorizontal: 10,
      paddingVertical: 7,
    },
    knowledgeSummaryButtonDisabled: {
      opacity: 0.64,
    },
    knowledgeSummaryButtonText: {
      fontSize: fontSize.xs,
      color: colors.primary,
      fontWeight: fontWeight.semibold,
    },
    knowledgeSummaryPreview: {
      maxHeight: 170,
      overflow: "hidden",
      borderRadius: radius.lg,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.background,
      paddingHorizontal: 12,
      paddingTop: 10,
      paddingBottom: 9,
    },
    knowledgeSummaryEmpty: {
      borderRadius: radius.lg,
      backgroundColor: colors.muted,
      color: colors.mutedForeground,
      fontSize: fontSize.sm,
      lineHeight: 20,
      paddingHorizontal: 12,
      paddingVertical: 14,
    },
    knowledgeSummaryUpdated: {
      marginTop: 8,
      paddingTop: 7,
      borderTopWidth: 0.5,
      borderTopColor: colors.border,
      fontSize: 11,
      color: colors.mutedForeground,
    },
    knowledgeSummaryMarkdownBody: {
      color: colors.mutedForeground,
      fontSize: fontSize.xs,
      lineHeight: 18,
    },
    knowledgeSummaryMarkdownHeading: {
      color: colors.foreground,
      fontSize: fontSize.xs,
      lineHeight: 18,
      fontWeight: fontWeight.semibold,
      marginTop: 0,
      marginBottom: 4,
    },
    knowledgeSummaryMarkdownParagraph: {
      color: colors.mutedForeground,
      fontSize: fontSize.xs,
      lineHeight: 18,
      marginTop: 0,
      marginBottom: 5,
    },
    knowledgeSummaryMarkdownList: {
      marginTop: 0,
      marginBottom: 4,
    },
    knowledgeSummaryMarkdownListItem: {
      color: colors.mutedForeground,
      fontSize: fontSize.xs,
      lineHeight: 18,
      marginBottom: 2,
    },
    knowledgeSummaryMarkdownStrong: { fontWeight: fontWeight.semibold },
    knowledgeSummaryMarkdownEm: { fontStyle: "italic" },
    knowledgeSummaryMarkdownLink: { color: colors.primary, textDecorationLine: "none" },
    knowledgeSummaryMarkdownQuote: {
      borderLeftWidth: 2,
      borderLeftColor: withOpacity(colors.primary, 0.4),
      paddingLeft: 8,
      marginLeft: 0,
      marginVertical: 4,
      backgroundColor: "transparent",
    },
    knowledgeSummaryMarkdownCode: {
      backgroundColor: colors.muted,
      color: colors.foreground,
      fontSize: fontSize.xs,
      paddingHorizontal: 4,
      paddingVertical: 1,
      borderRadius: radius.sm,
    },
    knowledgeEmptySources: {
      borderRadius: radius.lg,
      backgroundColor: colors.muted,
      color: colors.mutedForeground,
      fontSize: fontSize.sm,
      lineHeight: 20,
      paddingHorizontal: 12,
      paddingVertical: 14,
    },
    knowledgeSourceList: { gap: 8 },
    knowledgeSourceItem: {
      borderRadius: radius.lg,
      borderWidth: 0.5,
      borderColor: colors.border,
      backgroundColor: colors.background,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    knowledgeSourceActionRow: {
      marginTop: 9,
      paddingTop: 8,
      borderTopWidth: 0.5,
      borderTopColor: colors.border,
      alignItems: "flex-end",
    },
    knowledgeSourceAction: {
      minHeight: 30,
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      borderRadius: radius.sm,
      paddingHorizontal: 8,
      paddingVertical: 5,
      backgroundColor: withOpacity(colors.primary, 0.08),
    },
    knowledgeSourceActionText: {
      fontSize: fontSize.xs,
      color: colors.primary,
      fontWeight: fontWeight.semibold,
    },
    knowledgeSourceText: { fontSize: fontSize.sm, lineHeight: 20, color: colors.foreground },
    knowledgeSourceChapter: {
      marginTop: 6,
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
    },
    chapterGroup: { marginBottom: 16 },
    chapterDivider: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 8 },
    chapterLine: { flex: 1, height: 0.5, backgroundColor: colors.border },
    chapterName: {
      fontSize: fontSize.xs,
      fontWeight: fontWeight.medium,
      color: colors.mutedForeground,
      paddingHorizontal: 8,
    },
    noteCard: {
      backgroundColor: colors.card,
      borderRadius: radius.lg,
      borderWidth: 0.5,
      borderColor: colors.border,
      padding: 12,
      marginBottom: 8,
    },
    noteCardTop: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
    colorDot: { width: 10, height: 10, borderRadius: 5, marginTop: 4 },
    noteQuote: { flex: 1, fontSize: fontSize.sm, color: colors.foreground, lineHeight: 20 },
    noteBody: {
      marginTop: 8,
      backgroundColor: colors.muted,
      borderRadius: radius.sm,
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    noteText: { fontSize: fontSize.xs, color: colors.mutedForeground, lineHeight: 16 },
    noteActions: { flexDirection: "row", justifyContent: "flex-end", gap: 4, marginTop: 8 },
    noteActionBtn: { padding: 6, borderRadius: radius.sm },
    editArea: { marginTop: 8 },
    editorContainer: {
      flex: 1,
      minHeight: 180,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: "hidden",
    },
    editInput: {
      minHeight: 80,
      backgroundColor: colors.muted,
      borderRadius: radius.md,
      padding: 12,
      fontSize: fontSize.sm,
      color: colors.foreground,
      textAlignVertical: "top",
    },
    editTabs: { flexDirection: "row", gap: 12, marginBottom: 8, paddingHorizontal: 4 },
    editTabBtn: { paddingBottom: 4 },
    editTabBtnActive: { borderBottomWidth: 2, borderBottomColor: colors.primary },
    editTabText: {
      fontSize: fontSize.xs,
      color: colors.mutedForeground,
      fontWeight: fontWeight.medium,
    },
    editTabTextActive: { color: colors.primary },
    editPreviewArea: {
      minHeight: 80,
      backgroundColor: colors.muted,
      borderRadius: radius.md,
      padding: 12,
    },
    editActions: { flexDirection: "row", justifyContent: "flex-end", gap: 8, marginTop: 8 },
    editCancelBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: radius.md,
    },
    editCancelText: { fontSize: fontSize.xs, color: colors.mutedForeground },
    editSaveBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      backgroundColor: colors.primary,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: radius.md,
    },
    editSaveText: { fontSize: fontSize.xs, color: colors.primaryForeground },
    highlightCard: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
      backgroundColor: colors.card,
      borderRadius: radius.lg,
      borderWidth: 0.5,
      borderColor: colors.border,
      padding: 12,
      marginBottom: 8,
    },
    highlightBody: { flex: 1, minWidth: 0 },
    highlightText: { fontSize: fontSize.sm, color: colors.foreground, lineHeight: 20 },
    highlightChapter: { fontSize: fontSize.xs, color: colors.mutedForeground, marginTop: 4 },
    highlightDeleteBtn: { padding: 6, borderRadius: radius.sm },
    exportOverlay: { flex: 1 },
    exportDropdown: {
      position: "absolute",
      top: 56,
      right: 16,
      minWidth: 176,
      backgroundColor: colors.card,
      borderRadius: radius.lg,
      borderWidth: 0.5,
      borderColor: colors.border,
      padding: 4,
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },
    exportItem: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: radius.md },
    exportItemDisabled: { opacity: 0.5 },
    exportDivider: { height: 0.5, backgroundColor: colors.border, marginVertical: 4 },
    exportItemText: { fontSize: fontSize.sm, color: colors.foreground },
  });
